### ISSUE TITLE
Displaying and loading - camool .json files

### ISSUE THREAD

**Issue by alexGH666** [tmeedend/camtool#18]
For some tracks/camtool file combinations, the old camtool2 would'nt display available files. For example for seb's file for Glava Zete (https://www.racedepartment.com/downloads/camtool-for-glava-zete-1-0.41221/). But you could at least load it manually knowning the name of the file. In this case via "Settings->Load", entering "seb" end pressing "load". This seems broken now in your faboulous new version. For some reason it would load the json-file. A fix would be very welcome. Fixing the bug in the orignal camtool2 which prevents some json-files from displaying would be even nicer. Thanks nevertheless for this new version of camtool which is soooo much faster fps-wise. :-)

**Comment by tmeedend** [comment]
As I am trying to reorganize the code, there is good chances that I break stuff while doing so. Thank you for reporting this. I’m going to try to fix the whole thing :)

**Comment by tmeedend** [comment]
I have fixed the problem. It's on the develop branch.
I don't manage to reproduce the fact that we cannot load the data by writing it's name. It seems fixed also but I don't know what I did.

**Comment by alexGH666** [comment]
Thank you very much. Your work is very much appreciated. Will test it and give you feedback if I can reproduce it.

**Comment by alexGH666** [comment]
Justed tested the fix. But although I seem to have placed all in it's place camtool isn't there anymore. Using the develop brach version, Camtool disappeard from the Apps sidebar in Assetto and also doesn't show up when you I use the search-function looking for "tool" or "cam". Rolling back to the last of your versions (downloaded from racedepartment) camtool shows up again, but obviously still maintains the bug.

What I did was:
- going to the develop-branch downloading the develop version as ZIP via github green "code" button
- deleting the old Camtool 2 folder under C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\apps\python
- unpacking the develop version in the same folder
- checking and double checking if all files are in their right place
- starting up assetto => camtool missing from apps
- just to be sure I disabled and reenabled Camtool in Contentmanager unter Settings->Assetto Corsa-Apps => camtool still missing
- then I deleted the develop-version and restore the previous version from a backup-zip I created before
- => camtool reappears

Strange. Any ideas?

**Comment by tmeedend** [comment]
Can you open the python debug app and send me the error that must be showing? I must have forgot to push something.
Thank you for your help!

**Comment by tmeedend** [comment]
I think I fixed it. I have also finished the new option to manage settings preferences and save them.
Can you try and tell me if it's ok for you please? If it's ok, I am going to release the app I think.

**Comment by alexGH666** [comment]
Yes, you fixed it man! Great work. I tried to load several data files. Every time the .json files showed up and it worked. Thanx!!!

**Comment by alexGH666** [comment]
Oopps, from my point of view this could be closed. Not sure if this should be up to you. So I reopened it. If you're ok with it close the issue :-)

**Comment by tmeedend** [comment]
thanks for your help! We can close it 👍
