### ISSUE TITLE
Camera issues when car is fast

### ISSUE THREAD

**Issue by tmeedend** [tmeedend/camtool#20]
problem here: https://www.youtube.com/watch?v=CR6Q2e2iqYc
From THE Giulliano Larin: 

Hi.
So far, amazing performance gain. I've been testing replays on different conditions and it is pretty stable.

However I've noticed an issue with the tracking. This is more pronou
[drag_camtool_test.zip](https://github.com/tmeedend/camtool/files/7581105/drag_camtool_test.zip)
nced in "drone" shots close to the car, moving at high speed. In testing I disabled the tracking offset (0) and used the tracking at 100% and the problem persisted. Then, I tried with 0% tracking, just by animating the camera and there were no issues; so the problem is not related to camera position (x,y,z) but to camera orientation. Perhaps something related to interpolation?
Anyway, great work so far. 

On the original app this does not happen. The only instance is when the car runs over the red lines (track boundaries), but I believe this is not related to what I'm reporting here.
I have 3 camera sets for the drag strip. I recommend using a fast car. It is perfect for reproducing this scenario:

01 - 100 tracking/ 0 offset/
02 - 0 tracking/ 0 offset/ cam animation only
03 - 50 tracking/ 04 offset + cam animation

**Comment by tmeedend** [comment]
I can clearly reproduce this bug with the data you gave and an F1 car.

**Comment by ATRcamtools** [comment]
Hi Gil! I too noticed some stuttering but in my system it does not reproduce everytime the same way. Sometimes the stuttering is pretty noticible and rewinding and playing again it smothes 90% in some cases. I know you said it didn't happened before. But yep, this is what we have rn and I think it would vanish if the performance keep improving. Do you happen to use the spline method?
